"""revised database design for image tags colors

Revision ID: 3f0705b302c0
Revises: 54d4ce82f808
Create Date: 2025-11-10 21:12:00.334522

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f0705b302c0"
down_revision: Union[str, None] = "54d4ce82f808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.add_column(
        "image_metadata",
        sa.Column("tag_vec", Vector(dim=4096), nullable=True),
    )
    op.add_column(
        "image_metadata",
        sa.Column("color_vec", Vector(dim=12), nullable=True),
    )
    op.drop_column("image_metadata", "tags")
    op.drop_column("image_metadata", "colors")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image_metadata",
        sa.Column(
            "colors",
            postgresql.ARRAY(sa.VARCHAR(length=7)),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "image_metadata",
        sa.Column(
            "tags", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("image_metadata", "color_vec")
    op.drop_column("image_metadata", "tag_vec")
    # ### end Alembic commands ###
