"""change model base owner_id -> user_id

Revision ID: 54d4ce82f808
Revises: c3906896448e
Create Date: 2025-11-10 17:28:18.638193

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54d4ce82f808"
down_revision: Union[str, None] = "c3906896448e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "image_metadata_owner_id_fkey", "image_metadata", type_="foreignkey"
    )
    op.drop_column("image_metadata", "owner_id")
    op.drop_constraint("images_owner_id_fkey", "images", type_="foreignkey")
    op.drop_column("images", "owner_id")
    op.add_column("item", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.drop_constraint("item_owner_id_fkey", "item", type_="foreignkey")
    op.create_foreign_key(
        None,
        "item",
        "users",
        ["user_id"],
        ["id"],
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.drop_column("item", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item", sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "item", type_="foreignkey")
    op.create_foreign_key(
        "item_owner_id_fkey",
        "item",
        "users",
        ["owner_id"],
        ["id"],
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.drop_column("item", "user_id")
    op.add_column(
        "images", sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        "images_owner_id_fkey",
        "images",
        "users",
        ["owner_id"],
        ["id"],
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.add_column(
        "image_metadata",
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "image_metadata_owner_id_fkey",
        "image_metadata",
        "users",
        ["owner_id"],
        ["id"],
        referent_schema="auth",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
