"""add tables for colors and tags

Revision ID: b2b4671c4752
Revises: 3f0705b302c0
Create Date: 2025-11-10 21:33:25.811977

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b2b4671c4752"
down_revision: Union[str, None] = "3f0705b302c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "colors",
        sa.Column("hex", postgresql.CITEXT(), nullable=False),
        sa.PrimaryKeyConstraint("hex"),
    )
    op.create_table(
        "tags",
        sa.Column("name", postgresql.CITEXT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "image_colors",
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("color_hex", postgresql.CITEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["color_hex"],
            ["colors.hex"],
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.PrimaryKeyConstraint("image_id", "color_hex"),
    )
    op.create_table(
        "image_tags",
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("tag_name", postgresql.CITEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_name"],
            ["tags.name"],
        ),
        sa.PrimaryKeyConstraint("image_id", "tag_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image_tags")
    op.drop_table("image_colors")
    op.drop_table("tags")
    op.drop_table("colors")
    # ### end Alembic commands ###
