"""add constraints on images related table

Revision ID: f464d8e1c488
Revises: b2b4671c4752
Create Date: 2025-11-12 13:55:52.695184

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f464d8e1c488"
down_revision: Union[str, None] = "b2b4671c4752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("image_colors_image_id_fkey", "image_colors", type_="foreignkey")
    op.create_foreign_key(
        None,
        "image_colors",
        "images",
        ["image_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "image_metadata_user_id_fkey", "image_metadata", type_="foreignkey"
    )
    op.drop_constraint(
        "image_metadata_image_id_fkey", "image_metadata", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "image_metadata",
        "users",
        ["user_id"],
        ["id"],
        referent_schema="auth",
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "image_metadata",
        "images",
        ["image_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("image_tags_image_id_fkey", "image_tags", type_="foreignkey")
    op.create_foreign_key(
        None,
        "image_tags",
        "images",
        ["image_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "image_tags", type_="foreignkey")
    op.create_foreign_key(
        "image_tags_image_id_fkey", "image_tags", "images", ["image_id"], ["id"]
    )
    op.drop_constraint(None, "image_metadata", type_="foreignkey")
    op.drop_constraint(None, "image_metadata", type_="foreignkey")
    op.create_foreign_key(
        "image_metadata_image_id_fkey",
        "image_metadata",
        "images",
        ["image_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "image_metadata_user_id_fkey",
        "image_metadata",
        "users",
        ["user_id"],
        ["id"],
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "image_colors", type_="foreignkey")
    op.create_foreign_key(
        "image_colors_image_id_fkey", "image_colors", "images", ["image_id"], ["id"]
    )
    # ### end Alembic commands ###
